# Gruvbox Dark Colors
set -g status-bg "colour237"
set -g status-fg "colour245"
set -g status-left '#[bold,bg=colour236,fg=colour248] #S '
set -g status-right '#[bold,bg=colour236,fg=colour248] %d/%m %H:%M:%S '

setw -g window-status-current-format "#[bold,bg=colour236,fg=colour223] #I:#W "
setw -g window-status-format " #I:#W "

set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour245
set -g message-style bg=colour237,fg=colour245

