# Gruvbox Light Colors
set -g status-bg "colour250"
set -g status-fg "colour237"
set -g status-left '#[bold,bg=colour252,fg=colour237] #S '
set -g status-right '#[bold,bg=colour252,fg=colour237] %d/%m %H:%M:%S '

setw -g window-status-current-format "#[bold,bg=colour252,fg=colour234] #I:#W "
setw -g window-status-format " #I:#W "

set -g pane-border-style fg=colour250
set -g pane-active-border-style fg=colour237
set -g message-style bg=colour250,fg=colour237

